[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm prisma generate",
  "pnpm run build",
  "cp -r public .next/standalone/public || true",
  "cp -r .next/static .next/standalone/.next/static || true"
]

[start]
cmd = "node .next/standalone/server.js"