[phases.setup]
nixPkgs = ["...", "yt-dlp", "ffmpeg", "python3", "curl", "openssl"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pnpm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm exec prisma generate", "pnpm run build"]

[start]
cmd = "pnpm run start"